### ISSUE TITLE
Can't get attached devices

### ISSUE THREAD

**Issue by lolpold** [gruijter/com.gruijter.netgear#33]
Hi!

Having some issues getting attached devices when updating router and Homey firmwares. 
Installed your beta app for the 3.0.0 but no attached devices. Would you mind looking at it?

**Comment by lolpold** [comment]
========== STARTING TEST ==========
Node version: v8.16.0
Netgear package version: 3.9.5
OS: linux 4.14.15-g81f15bab94
Info: Homey fw:3.0.0-rc.16 app: 3.0.0
t = 0
trying to auto discover Netgear routers...
[{Firmware:V1.0.1.100WW,RegionTag:RAX120_WW,Region:ww,Model:RAX120,InternetConnectionStatus:Up,SOAPVersion:3.34,ReadyShareSupportedLevel:25,XCloudSupported:1,isBlankState:0,LoginMethod:2.0,host:10.0.0.1,port:80}]
t = 3.83
trying to login...
login method: 2
t = 3.887
trying to getInfo...
{Description:Netgear Smart Wizard 3.0, specification 1.6 version,SmartAgentversion:3.0,FirewallVersion:net-wall 2.0,OthersoftwareVersion:N/A,Otherhardwareversion:N/A,FirstUseDate:Sunday, 30 Sep 2007 01:10:03,DeviceMode:0,DeviceNameUserSet:false,ModelName:RAX120,SerialNumber:**********,Firmwareversion:V1.0.1.100,Hardwareversion:RAX120,DeviceName:RAX120,FirmwareDLmethod:Null,FirmwareLastChecked:2019_9.19_13:14:17,DeviceModeCapability:0;1;2}
t = 3.953
trying to get System Uptime (hh:mm:ss)...
000:25:43
t = 3.994
trying to getSystemInfo...
{NewCPUUtilization:12,NewPhysicalMemory:32,NewMemoryUtilization:44,NewPhysicalFlash:128,NewAvailableFlash:57.98}
t = 12.053
trying to get supportFeatures...
{DynamicQoS:1.0,AccessControl:1.0,SpeedTest:2.0,GuestNetworkSchedule:1.0,TCAcceptance:1.0,DeviceTypeIdentification:1.0,AttachedDevice:2.0,NameNTGRDevice:1.0,SmartConnect:2.0,MaxMonthlyTrafficLimitation:4095000000,SupportXMLEncoded:1.0,SupportAXMode:1,SupportWPA3:1}
t = 12.161
trying to get the Device configuration...
{BlankState:0,NewBlockSiteEnable:0,NewBlockSiteName:0,NewTimeZone:+01:00GMT,M3.5.0/2:00,M10.5.0/2:00,NewDaylightSaving:1}
t = 12.241
trying to get the LAN configuration...
{NewLANSubnet:255.255.255.0,NewWANLAN_Subnet_Match:0,NewLANMACAddress:0836C9181DDB,NewLANIP:10.0.0.1,NewDHCPEnabled:true}
t = 12.311
trying to get the WAN configuration...
{NewEnable:1,NewConnectionType:DHCP,NewAddressingType:DHCP,NewMACAddress:0836C9181DDC,NewMACAddressOverride:0,NewDNSEnabled:1,NewExternalIPAddress:92.32.241.161,NewSubnetMask:255.255.248.0,NewDefaultGateway:92.32.240.1,NewMaxMTUSize:1500,NewDNSServers:81.26.228.3 81.26.227.3}
t = 12.382
trying to get Parental Control Status...
404 Not Found. The requested function/page is not available
Parental Control Enabled: [object Object]
t = 12.529
trying to get Qos Status...
Qos Enabled: false
t = 12.569
trying to get Qos Bandwidth options...
{newUplinkBandwidth:0,newDownlinkBandwidth:0,enabled:2}
t = 12.617
trying to get Device Access Control Status...
Block Device Enabled: true
t = 12.661
trying to get attachedDevices method 1...
Number of attached devices: 0
First attached device: undefined
t = 17.294
trying to get attachedDevices method 2...
no response code from router
{lastResponse:\r\n

**Comment by lolpold** [comment]
By the way, this is how it looks when trying to use port 443 when testing:

========== STARTING TEST ==========
Node version: v8.16.0
Netgear package version: 3.9.5
OS: linux 4.14.15-g81f15bab94
Info: Homey fw:3.0.0-rc.16 app: 3.0.0
t = 0
trying to auto discover Netgear routers...
[{Firmware:V1.0.1.100WW,RegionTag:RAX120_WW,Region:ww,Model:RAX120,InternetConnectionStatus:Up,SOAPVersion:3.34,ReadyShareSupportedLevel:25,XCloudSupported:1,isBlankState:0,LoginMethod:2.0,host:10.0.0.1,port:80}]
t = 3.799
trying to login...
{message:Failed to login}
{host:10.0.0.1,port:443,tls:false,username:admin,password:*****,timeout:18000,sessionId:A7D88AE69687E58D9A00,loggedIn:false,configStarted:false,soapVersion:3,loginMethod:2.22,checkNewFirmwareMethod:2,guestWifiMethod:{get50_1:1},lastResponse:{message:socket hang up,code:ECONNRESET}}

**Comment by gruijter** [comment]
`trying to get attachedDevices method 2...
no response code from router
{lastResponse:\r\n`

The test log stops there with nothing after it?

**Comment by lolpold** [comment]
Yes , nothing else there.
![Screenshot_20191016-214100_Homey](https://user-images.githubusercontent.com/6950290/66952954-e0768800-f05d-11e9-82df-69f0def064b0.jpg)

**Comment by gruijter** [comment]
did you already try a power cycle of the router?

**Comment by lolpold** [comment]
Yes, I rebooted the device > uninstalled the app > installed again > added device > ran test.
Now I PTP and still nothing with the same test result.

**Comment by gruijter** [comment]
and in the orbi app you do see the right number of attached devices?

**Comment by lolpold** [comment]
This is my log. 

2019-10-16 22:00:43 [netgear] [0] Logging in
2019-10-16 21:59:52 [err] [ManagerDrivers] [netgear] [0] updateRouterDeviceState error: Not logged in
2019-10-16 21:59:47 [log] [MyApp] Router compatibility test started
2019-10-16 21:59:06 [log] [MyApp] Router compatibility test started
2019-10-16 21:58:51 [log] [MyApp] Router discovery started
2019-10-16 21:58:48 [log] [MyApp] Retrieving known devices list
2019-10-16 21:58:46 [log] [MyApp] Retrieving known devices list
2019-10-16 21:57:20 [netgear] [0] Access control enable requested
2019-10-16 20:59:08 [log] [MyApp] app unload called
2019-10-16 20:59:08 [err] [MyApp] unhandledRejection! Error [ERR_IPC_CHANNEL_CLOSED]: channel closed at process.target.send (internal/child_process.js:578:16) at Promise (/opt/homey-client/system/manager/ManagerApps/bootstrap/sdk/v2/lib/HomeyClient.js:1:663) at new Promise () at HomeyClient.emit (/opt/homey-client/system/manager/ManagerApps/bootstrap/sdk/v2/lib/HomeyClient.js:1:514) at SDK._onManagerCall (/opt/homey-client/system/manager/ManagerApps/bootstrap/sdk/v2/lib/SDK.js:1:4195) at ManagerDrivers._onDriverEmit (/opt/homey-client/system/manager/ManagerApps/bootstrap/sdk/v2/manager/drivers.js:1:2556) at NetgearDriver.__onDeviceEmit (/opt/homey-client/system/manager/ManagerApps/bootstrap/sdk/v2/lib/Driver.js:1:3726) at Object.emit (/opt/homey-client/system/manager/ManagerApps/bootstrap/sdk/v2/lib/Driver.js:1:2109) at NetgearDevice.setStoreValue (/opt/homey-client/system/manager/ManagerApps/bootstrap/sdk/v2/lib/Device.js:1:6781) at Homey.on (/drivers/netgear/device.js:349:16)
2019-10-16 20:59:08 [err] [MyApp] unhandledRejection! Error [ERR_IPC_CHANNEL_CLOSED]: channel closed at process.target.send (internal/child_process.js:578:16) at Promise (/opt/homey-client/system/manager/ManagerApps/bootstrap/sdk/v2/lib/HomeyClient.js:1:663) at new Promise () at HomeyClient.emit (/opt/homey-client/system/manager/ManagerApps/bootstrap/sdk/v2/lib/HomeyClient.js:1:514) at SDK._onManagerCall (/opt/homey-client/system/manager/ManagerApps/bootstrap/sdk/v2/lib/SDK.js:1:4195) at ManagerDrivers._onDriverEmit (/opt/homey-client/system/manager/ManagerApps/bootstrap/sdk/v2/manager/drivers.js:1:2556) at NetgearDriver.__onDeviceEmit (/opt/homey-client/system/manager/ManagerApps/bootstrap/sdk/v2/lib/Driver.js:1:3726) at Object.emit (/opt/homey-client/system/manager/ManagerApps/bootstrap/sdk/v2/lib/Driver.js:1:2109) at NetgearDevice.setStoreValue (/opt/homey-client/system/manager/ManagerApps/bootstrap/sdk/v2/lib/Device.js:1:6781) at Homey.on (/drivers/netgear/device.js:349:16)
2019-10-16 20:59:08 [err] [MyApp] unhandledRejection! Error [ERR_IPC_CHANNEL_CLOSED]: channel closed at process.target.send (internal/child_process.js:578:16) at Promise (/opt/homey-client/system/manager/ManagerApps/bootstrap/sdk/v2/lib/HomeyClient.js:1:663) at new Promise () at HomeyClient.emit (/opt/homey-client/system/manager/ManagerApps/bootstrap/sdk/v2/lib/HomeyClient.js:1:514) at SDK._onManagerCall (/opt/homey-client/system/manager/ManagerApps/bootstrap/sdk/v2/lib/SDK.js:1:4195) at ManagerDrivers._onDriverEmit (/opt/homey-client/system/manager/ManagerApps/bootstrap/sdk/v2/manager/drivers.js:1:2556) at NetgearDriver.__onDeviceEmit (/opt/homey-client/system/manager/ManagerApps/bootstrap/sdk/v2/lib/Driver.js:1:3726) at Object.emit (/opt/homey-client/system/manager/ManagerApps/bootstrap/sdk/v2/lib/Driver.js:1:2109) at NetgearDevice.setStoreValue (/opt/homey-client/system/manager/ManagerApps/bootstrap/sdk/v2/lib/Device.js:1:6781) at Homey.on (/drivers/netgear/device.js:349:16)
2019-10-16 20:59:08 [netgear] [0] unload called, storing knownDevices state
2019-10-16 20:59:08 [netgear] [0] unload called, storing knownDevices state
2019-10-16 20:59:08 [netgear] [0] unload called, storing knownDevices state
2019-10-16 20:59:07 [log] [MyApp] app unload called
2019-10-16 20:55:43 [err] [ManagerDrivers] [netgear] [0] updateRouterDeviceState error: invalid_device_by_appid
2019-10-16 20:55:43 [netgear] [0] { Error: invalid_device_by_appid at Remote IPC Process message: 'invalid_device_by_appid', code: 404 } attached_devices 0
2019-10-16 20:55:36 [netgear] [0] router deleted as device
2019-10-16 20:48:02 [netgear] [0] Access control enable requested
2019-10-16 20:48:01 [netgear] [0] Traffic meter enable requested
2019-10-16 20:48:01 [netgear] [0] retrieving knownDevices from persistent storage
2019-10-16 20:48:01 [netgear] [0] device init: RAX120 id: 5F719354F0208
2019-10-16 20:47:51 [netgear] [0] router device settings changed
2019-10-16 20:47:10 [netgear] [0] Logging in
2019-10-16 20:46:49 [err] [ManagerDrivers] [netgear] [0] updateRouterDeviceState error: Not logged in
2019-10-16 20:46:15 [log] [MyApp] Router compatibility test started
2019-10-16 20:46:03 [log] [MyApp] Router discovery started
2019-10-16 20:45:47 [netgear] [0] Access control enable requested
2019-10-16 20:45:46 [netgear] [0] Traffic meter enable requested
2019-10-16 20:45:46 [netgear] [0] retrieving knownDevices from persistent storage
2019-10-16 20:45:46 [netgear] [0] device init: RAX120 id: 5F719354F0208
2019-10-16 20:45:36 [netgear] [0] router device settings changed
2019-10-16 20:44:09 [netgear] [0] Access control enable requested
2019-10-16 20:44:08 [netgear] [0] Traffic meter enable requested
2019-10-16 20:44:08 [netgear] [0] retrieving knownDevices from persistent storage
2019-10-16 20:44:08 [attached_device] [0] device init Leopold
2019-10-16 20:44:08 [attached_device] AttachedDeviceDriver onInit
2019-10-16 20:44:08 [netgear] [0] device init: RAX120 id: 5F719354F0208
2019-10-16 20:44:08 [netgear] NetgearDriver onInit
2019-10-16 20:44:01 [log] [MyApp] app unload called
2019-10-16 20:43:56 [log] [MyApp] Retrieving known devices list
2019-10-16 20:36:56 [attached_device] [0] Disconnected: Leopold
2019-10-16 20:36:20 [attached_device] [0] 6C:C7:EC:61:35:73 added: Leopold
2019-10-16 20:36:20 [attached_device] [0] device init Leopold
2019-10-16 20:35:39 [attached_device] pairing started by user
2019-10-16 20:32:43 [netgear] [0] Access control enable requested
2019-10-16 20:29:20 [log] [MyApp] app unload called
2019-10-16 20:29:20 [err] [MyApp] unhandledRejection! Error [ERR_IPC_CHANNEL_CLOSED]: channel closed at process.target.send (internal/child_process.js:578:16) at Promise (/opt/homey-client/system/manager/ManagerApps/bootstrap/sdk/v2/lib/HomeyClient.js:1:663) at new Promise () at HomeyClient.emit (/opt/homey-client/system/manager/ManagerApps/bootstrap/sdk/v2/lib/HomeyClient.js:1:514) at SDK._onManagerCall (/opt/homey-client/system/manager/ManagerApps/bootstrap/sdk/v2/lib/SDK.js:1:4195) at ManagerDrivers._onDriverEmit (/opt/homey-client/system/manager/ManagerApps/bootstrap/sdk/v2/manager/drivers.js:1:2556) at NetgearDriver.__onDeviceEmit (/opt/homey-client/system/manager/ManagerApps/bootstrap/sdk/v2/lib/Driver.js:1:3726) at Object.emit (/opt/homey-client/system/manager/ManagerApps/bootstrap/sdk/v2/lib/Driver.js:1:2109) at NetgearDevice.setStoreValue (/opt/homey-client/system/manager/ManagerApps/bootstrap/sdk/v2/lib/Device.js:1:6781) at Homey.on (/drivers/netgear/device.js:349:16)
2019-10-16 20:29:19 [netgear] [0] unload called, storing knownDevices state
2019-10-16 20:29:19 [log] [MyApp] app unload called
2019-10-16 20:28:40 [log] [MyApp] Router compatibility test started
2019-10-16 20:28:30 [log] [MyApp] Router compatibility test started
2019-10-16 20:28:16 [log] [MyApp] Router discovery started
2019-10-16 20:27:19 [netgear] [0] New device mode selected: Router
2019-10-16 20:26:56 [netgear] [0] Access control enable requested
2019-10-16 20:26:54 [netgear] [0] Traffic meter enable requested
2019-10-16 20:26:54 [netgear] [0] retrieving knownDevices from persistent storage
2019-10-16 20:26:54 [netgear] [0] Migration to V3 ready. CHECK YOUR FLOWS! (sorry)
2019-10-16 20:26:47 [netgear] [0] Migrating device to Homey V3.
2019-10-16 20:26:47 [netgear] [0] device init: RAX120 id: 5F719354F0208
2019-10-16 20:26:47 [netgear] NetgearDriver onInit
2019-10-16 12:57:10 [log] [MyApp] app unload called
2019-10-16 12:37:16 [netgear] [0] login succsesfull @ driver
2019-10-16 12:36:06 [err] [ManagerDrivers] [netgear] [0] updateRouterDeviceState error: Not logged in
2019-10-16 12:36:06 [netgear] [0] "\r\n\r\n\r\n\r\n401\r\n\r\n\r\n"
2019-10-16 12:36:06 [netgear] [0] last repsonse from router:
2019-10-16 11:35:22 [netgear] [0] login succsesfull @ driver
2019-10-16 11:34:12 [err] [ManagerDrivers] [netgear] [0] updateRouterDeviceState error: Not logged in
2019-10-16 11:34:12 [netgear] [0] "\r\n\r\n\r\n\r\n401\r\n\r\n\r\n"
2019-10-16 11:34:12 [netgear] [0] last repsonse from router:
2019-10-16 10:33:28 [netgear] [0] login succsesfull @ driver
2019-10-16 10:32:18 [err] [ManagerDrivers] [netgear] [0] updateRouterDeviceState error: Not logged in
2019-10-16 10:32:18 [netgear] [0] "\r\n\r\n\r\n\r\n401\r\n\r\n\r\n"
2019-10-16 10:32:18 [netgear] [0] last repsonse from router:
2019-10-16 09:31:34 [netgear] [0] login succsesfull @ driver
2019-10-16 09:30:24 [err] [ManagerDrivers] [netgear] [0] updateRouterDeviceState error: Not logged in
2019-10-16 09:30:24 [netgear] [0] "\r\n\r\n\r\n\r\n401\r\n\r\n\r\n"
2019-10-16 09:30:24 [netgear] [0] last repsonse from router:
2019-10-16 08:29:39 [netgear] [0] login succsesfull @ driver
2019-10-16 08:28:29 [err] [ManagerDrivers] [netgear] [0] updateRouterDeviceState error: Not logged in
2019-10-16 08:28:29 [netgear] [0] "\r\n\r\n\r\n\r\n401\r\n\r\n\r\n"
2019-10-16 08:28:29 [netgear] [0] last repsonse from router:
2019-10-16 07:27:45 [netgear] [0] login succsesfull @ driver
2019-10-16 07:26:35 [err] [ManagerDrivers] [netgear] [0] updateRouterDeviceState error: Not logged in
2019-10-16 07:26:35 [netgear] [0] "\r\n\r\n\r\n\r\n401\r\n\r\n\r\n"
2019-10-16 07:26:35 [netgear] [0] last repsonse from router:
2019-10-16 06:25:50 [netgear] [0] login succsesfull @ driver
2019-10-16 06:24:40 [err] [ManagerDrivers] [netgear] [0] updateRouterDeviceState error: Not logged in
2019-10-16 06:24:40 [netgear] [0] "\r\n\r\n\r\n\r\n401\r\n\r\n\r\n"
2019-10-16 06:24:40 [netgear] [0] last repsonse from router:
2019-10-16 05:23:56 [netgear] [0] login succsesfull @ driver
2019-10-16 05:23:05 [err] [ManagerDrivers] [netgear] [0] updateRouterDeviceState error: Unauthorized. Incorrect username/password?
2019-10-16 05:23:05 [netgear] [0] "\r\n\r\n\r\n\r\n401\r\n\r\n\r\n"
2019-10-16 05:23:05 [netgear] [0] last repsonse from router:
2019-10-16 04:22:02 [netgear] [0] login succsesfull @ driver
2019-10-16 04:20:52 [err] [ManagerDrivers] [netgear] [0] updateRouterDeviceState error: Not logged in
2019-10-16 04:20:52 [netgear] [0] "\r\n\r\n\r\n\r\n401\r\n\r\n\r\n"
2019-10-16 04:20:52 [netgear] [0] last repsonse from router:
2019-10-16 03:20:07 [netgear] [0] login succsesfull @ driver
2019-10-16 03:18:57 [err] [ManagerDrivers] [netgear] [0] updateRouterDeviceState error: Not logged in
2019-10-16 03:18:57 [netgear] [0] "\r\n\r\n\r\n\r\n401\r\n\r\n\r\n"
2019-10-16 03:18:57 [netgear] [0] last repsonse from router:
2019-10-16 02:18:13 [netgear] [0] login succsesfull @ driver
2019-10-16 02:17:03 [err] [ManagerDrivers] [netgear] [0] updateRouterDeviceState error: Not logged in
2019-10-16 02:17:03 [netgear] [0] "\r\n\r\n\r\n\r\n401\r\n\r\n\r\n"
2019-10-16 02:17:03 [netgear] [0] last repsonse from router:
2019-10-16 01:16:19 [netgear] [0] login succsesfull @ driver
2019-10-16 01:15:09 [err] [ManagerDrivers] [netgear] [0] updateRouterDeviceState error: Not logged in
2019-10-16 01:15:09 [netgear] [0] "\r\n\r\n\r\n\r\n401\r\n\r\n\r\n"
2019-10-16 01:15:09 [netgear] [0] last repsonse from router:
2019-10-16 00:14:24 [netgear] [0] login succsesfull @ driver
2019-10-16 00:13:15 [err] [ManagerDrivers] [netgear] [0] updateRouterDeviceState error: Not logged in
2019-10-16 00:13:15 [netgear] [0] "\r\n\r\n\r\n\r\n401\r\n\r\n\r\n"
2019-10-16 00:13:15 [netgear] [0] last repsonse from router:
2019-10-15 23:12:30 [netgear] [0] login succsesfull @ driver
2019-10-15 23:11:20 [err] [ManagerDrivers] [netgear] [0] updateRouterDeviceState error: Not logged in
2019-10-15 23:11:20 [netgear] [0] "\r\n\r\n\r\n\r\n401\r\n\r\n\r\n"
2019-10-15 23:11:20 [netgear] [0] last repsonse from router:
2019-10-15 22:10:36 [netgear] [0] login succsesfull @ driver
2019-10-15 22:09:26 [err] [ManagerDrivers] [netgear] [0] updateRouterDeviceState error: Not logged in
2019-10-15 22:09:26 [netgear] [0] "\r\n\r\n\r\n\r\n401\r\n\r\n\r\n"
2019-10-15 22:09:26 [netgear] [0] last repsonse from router:
2019-10-15 21:23:54 [err] [ManagerDrivers] [netgear] [0] updateRouterDeviceState error: connect EHOSTUNREACH 10.0.0.1:80
2019-10-15 21:23:54 [netgear] [0] {"errno":"EHOSTUNREACH","code":"EHOSTUNREACH","syscall":"connect","address":"10.0.0.1","port":80}
2019-10-15 21:23:54 [netgear] [0] last repsonse from router:
2019-10-15 21:22:47 [err] [ManagerDrivers] [netgear] [0] updateRouterDeviceState error: connect EHOSTUNREACH 10.0.0.1:80
2019-10-15 21:22:47 [netgear] [0] {"errno":"EHOSTUNREACH","code":"EHOSTUNREACH","syscall":"connect","address":"10.0.0.1","port":80}
2019-10-15 21:22:47 [netgear] [0] last repsonse from router:
2019-10-15 21:08:42 [netgear] [0] login succsesfull @ driver
2019-10-15 21:07:32 [err] [ManagerDrivers] [netgear] [0] updateRouterDeviceState error: Not logged in
2019-10-15 21:07:32 [netgear] [0] "\r\n\r\n\r\n\r\n401\r\n\r\n\r\n"
2019-10-15 21:07:32 [netgear] [0] last repsonse from router:
2019-10-15 20:06:47 [netgear] [0] login succsesfull @ driver
2019-10-15 20:05:37 [err] [ManagerDrivers] [netgear] [0] updateRouterDeviceState error: Not logged in
2019-10-15 20:05:37 [netgear] [0] "\r\n\r\n\r\n\r\n401\r\n\r\n\r\n"
2019-10-15 20:05:37 [netgear] [0] last repsonse from router:
2019-10-15 19:04:53 [netgear] [0] login succsesfull @ driver
2019-10-15 19:03:43 [err] [ManagerDrivers] [netgear] [0] updateRouterDeviceState error: Not logged in
2019-10-15 19:03:43 [netgear] [0] "\r\n\r\n\r\n\r\n401\r\n\r\n\r\n"
2019-10-15 19:03:43 [netgear] [0] last repsonse from router:
2019-10-15 18:02:59 [netgear] [0] login succsesfull @ driver
2019-10-15 18:01:49 [err] [ManagerDrivers] [netgear] [0] updateRouterDeviceState error: Not logged in
2019-10-15 18:01:49 [netgear] [0] "\r\n\r\n\r\n\r\n401\r\n\r\n\r\n"
2019-10-15 18:01:49 [netgear] [0] last repsonse from router:
2019-10-15 18:00:39 [err] [ManagerDrivers] [netgear] [0] updateRouterDeviceState error: connect EHOSTUNREACH 10.0.0.1:80
2019-10-15 18:00:39 [netgear] [0] {"errno":"EHOSTUNREACH","code":"EHOSTUNREACH","syscall":"connect","address":"10.0.0.1","port":80}
2019-10-15 18:00:39 [netgear] [0] last repsonse from router:
2019-10-15 17:59:30 [err] [ManagerDrivers] [netgear] [0] updateRouterDeviceState error: connect EHOSTUNREACH 10.0.0.1:80
2019-10-15 17:59:30 [netgear] [0] {"errno":"EHOSTUNREACH","code":"EHOSTUNREACH","syscall":"connect","address":"10.0.0.1","port":80}
2019-10-15 17:59:30 [netgear] [0] last repsonse from router:
2019-10-15 17:27:56 [netgear] [0] login succsesfull @ driver
2019-10-15 17:26:46 [err] [ManagerDrivers] [netgear] [0] updateRouterDeviceState error: Not logged in
2019-10-15 17:26:46 [netgear] [0] "\r\n\r\n\r\n\r\n401\r\n\r\n\r\n"
2019-10-15 17:26:46 [netgear] [0] last repsonse from router:
2019-10-15 16:26:01 [netgear] [0] login succsesfull @ driver
2019-10-15 16:24:52 [err] [ManagerDrivers] [netgear] [0] updateRouterDeviceState error: Not logged in
2019-10-15 16:24:52 [netgear] [0] "\r\n\r\n\r\n\r\n401\r\n\r\n\r\n"
2019-10-15 16:24:52 [netgear] [0] last repsonse from router:
2019-10-15 16:23:43 [err] [ManagerDrivers] [netgear] [0] updateRouterDeviceState error: connect EHOSTUNREACH 10.0.0.1:80
2019-10-15 16:23:43 [netgear] [0] {"errno":"EHOSTUNREACH","code":"EHOSTUNREACH","syscall":"connect","address":"10.0.0.1","port":80}
2019-10-15 16:23:43 [netgear] [0] last repsonse from router:
2019-10-15 16:22:50 [err] [ManagerDrivers] [netgear] [0] updateRouterDeviceState error: socket hang up
2019-10-15 16:22:50 [netgear] [0] {"code":"ECONNRESET"}
2019-10-15 16:22:50 [netgear] [0] last repsonse from router:
2019-10-15 15:40:28 [netgear] [0] login succsesfull @ driver
2019-10-15 15:39:18 [err] [ManagerDrivers] [netgear] [0] updateRouterDeviceState error: Not logged in
2019-10-15 15:39:18 [netgear] [0] "\r\n\r\n\r\n\r\n401\r\n\r\n\r\n"
2019-10-15 15:39:18 [netgear] [0] last repsonse from router:
2019-10-15 14:38:34 [netgear] [0] login succsesfull @ driver
2019-10-15 14:37:24 [err] [ManagerDrivers] [netgear] [0] updateRouterDeviceState error: Not logged in
2019-10-15 14:37:24 [netgear] [0] "\r\n\r\n\r\n\r\n401\r\n\r\n\r\n"
2019-10-15 14:37:24 [netgear] [0] last repsonse from router:
2019-10-15 13:39:18 [err] [ManagerDrivers] [netgear] [0] updateRouterDeviceState error: socket hang up
2019-10-15 13:39:18 [netgear] [0] {"code":"ECONNRESET"}
2019-10-15 13:39:18 [netgear] [0] last repsonse from router:
2019-10-15 13:36:39 [netgear] [0] login succsesfull @ driver
2019-10-15 13:35:29 [err] [ManagerDrivers] [netgear] [0] updateRouterDeviceState error: Not logged in
2019-10-15 13:35:29 [netgear] [0] "\r\n\r\n\r\n\r\n401\r\n\r\n\r\n"
2019-10-15 13:35:29 [netgear] [0] last repsonse from router:
2019-10-15 12:34:44 [netgear] [0] login succsesfull @ driver
2019-10-15 12:33:34 [err] [ManagerDrivers] [netgear] [0] updateRouterDeviceState error: Not logged in
2019-10-15 12:33:34 [netgear] [0] "\r\n\r\n\r\n\r\n401\r\n\r\n\r\n"
2019-10-15 12:33:34 [netgear] [0] last repsonse from router:
2019-10-15 11:32:50 [netgear] [0] login succsesfull @ driver
2019-10-15 11:31:40 [err] [ManagerDrivers] [netgear] [0] updateRouterDeviceState error: Not logged in
2019-10-15 11:31:40 [netgear] [0] "\r\n\r\n\r\n\r\n401\r\n\r\n\r\n"
2019-10-15 11:31:40 [netgear] [0] last repsonse from router:
2019-10-15 10:30:55 [netgear] [0] login succsesfull @ driver
2019-10-15 10:29:45 [err] [ManagerDrivers] [netgear] [0] updateRouterDeviceState error: Not logged in
2019-10-15 10:29:45 [netgear] [0] "\r\n\r\n\r\n\r\n401\r\n\r\n\r\n"
2019-10-15 10:29:45 [netgear] [0] last repsonse from router:
2019-10-15 09:29:01 [netgear] [0] login succsesfull @ driver
2019-10-15 09:27:50 [err] [ManagerDrivers] [netgear] [0] updateRouterDeviceState error: Not logged in
2019-10-15 09:27:50 [netgear] [0] "\r\n\r\n\r\n\r\n401\r\n\r\n\r\n"
2019-10-15 09:27:50 [netgear] [0] last repsonse from router:
2019-10-15 08:27:06 [netgear] [0] login succsesfull @ driver
2019-10-15 08:25:56 [err] [ManagerDrivers] [netgear] [0] updateRouterDeviceState error: Not logged in
2019-10-15 08:25:56 [netgear] [0] "\r\n\r\n\r\n\r\n401\r\n\r\n\r\n"
2019-10-15 08:25:56 [netgear] [0] last repsonse from router:

**Comment by lolpold** [comment]
What a great catch @gruijter ! 
No I can't see them in the app when I power cycled the router. 
Does this mean that there is an issue with the Firmware that I am running?

**Comment by gruijter** [comment]
it seems so. you can try deleting the homey device to make sure that Homey polling it is not the cause. Did you ever get attached devices? did you update the firmware recently?

**Comment by lolpold** [comment]
Yes I have changed all settings,
Updated the firmware yesterday. 
And Updated to 3.0.0 today. 
I am installing the latest stable on my RAX120 as I type. 
Will check If it works on that!

**Comment by lolpold** [comment]
Attached devices worked perfectly up until yesterday but I wasnt First to come home today. So mightve been broken since then :)

**Comment by lolpold** [comment]
Yes, it is working on Firmware 1.0.0.84 but not on 1.0.1.100. 
The firmware 1.0.1.100 is a Hot fix firmware, maybe something else was troubled in that Firmware that they released. 
Sorry for taking up your time. 
Cheers for helping though! :)

**Comment by lolpold** [comment]
Downgraded to Firmware 1.0.0.84, now it works.

**Comment by gruijter** [comment]
Anytime 👍
