### ISSUE TITLE
Beta version does not work

### ISSUE THREAD

**Issue by ma-be** [gruijter/com.gruijter.netgear#36]
Hi,
the stable Homey firmware v3.0.0, ios stable Homey app and your Netgear app v3.0.2 beta cannot run a test.
Router R6350 added successfully (reported ok connected) but it is not showing any info. Any idea?
Thanks

**Comment by ma-be** [comment]
The diagnostic report:
f6864de2-7f52-4113-bbc6-bc53cc3998d1

**Comment by ma-be** [comment]
![65778334-4BB0-40E9-A60D-AEABB4E46BAF](https://user-images.githubusercontent.com/11045804/67903794-d334bf80-fb6c-11e9-8239-2461c3c4f25f.jpeg)

**Comment by ma-be** [comment]
Log:
2019-10-30 23:29:21 [netgear] [0] watchdog triggered, restarting Homey device now 
2019-10-30 23:28:22 [err] [ManagerDrivers] [netgear] [0] DevicePoll socket hang up 
2019-10-30 23:27:22 [err] [ManagerDrivers] [netgear] [0] DevicePoll socket hang up 
2019-10-30 23:26:21 [err] [ManagerDrivers] [netgear] [0] DevicePoll socket hang up 
2019-10-30 23:25:21 [err] [ManagerDrivers] [netgear] [0] DevicePoll socket hang up 
2019-10-30 23:24:21 [err] [ManagerDrivers] [netgear] [0] { Error: socket hang up at createHangUpError (_http_client.js:342:15) at Socket.socketOnEnd (_http_client.js:437:23) at emitNone (events.js:111:20) at Socket.emit (events.js:208:7) at endReadableNT (_stream_readable.js:1064:12) at _combinedTickCallback (internal/process/next_tick.js:139:11) at process._tickCallback (internal/process/next_tick.js:181:9) code: 'ECONNRESET' } 
2019-10-30 23:24:20 [netgear] [0] Access control enable requested 
2019-10-30 23:24:13 [netgear] [0] Traffic meter enable requested 
2019-10-30 23:24:13 [netgear] [0] retrieving knownDevices from persistent storage

**Comment by gruijter** [comment]
Does the app v2.5.4 work ok for you? Did you try a ptp of the router?

**Comment by ma-be** [comment]
The stable version works, but I experience the following issue:
https://github.com/gruijter/com.gruijter.netgear/issues/29

**Comment by ma-be** [comment]
PTP of router enabled the test funcionality (see the result). However there is still no info on the page of the “R6350 device” in ios homey app.

========== STARTING TEST ==========
Node version: v8.16.0
Netgear package version: 3.9.7
OS: linux 4.14.15-g81f15bab94
Info: Homey fw:3.0.0 app: 3.0.2
t = 0
trying to auto discover Netgear routers...
[{Firmware:V1.1.0.52_1.0.1WW,RegionTag:R6350_WW,Region:WW,Model:R6350,InternetConnectionStatus:UP,ParentalControlSupported:1,SOAPVersion:3.21,ReadyShareSupportedLevel:9,XCloudSupported:1,LoginMethod:2.0,host:192.168.1.1,port:5000}]
t = 3.602
trying to login...
login method: 2
t = 3.71
trying to getInfo...
{ModelName:R6350,Description:Netgear Smart Wizard 3.0, specification 0.8 version,SerialNumber:**********,Firmwareversion:V1.1.0.52,SmartAgentversion:3.0,FirewallVersion:ACOS NAT-Netfilter v1.0.0.1 (Linux cone NAT Hot Patch 06/21/2010),VPNVersion:N/A,OthersoftwareVersion:1.0.1,Hardwareversion:R6350,Otherhardwareversion:N/A,FirstUseDate:Thursday, 31 October 2019 07:49:10,DeviceName:R6350,FirmwareDLmethod:Null,FirmwareLastChecked:2019_10.31_7:43:15,DeviceMode:0}
t = 3.821
trying to get System Uptime (hh:mm:ss)...
socket hang up
{lastResponse:{message:socket hang up,code:ECONNRESET}}
{}
t = 4.555
trying to getSystemInfo...
socket hang up
{lastResponse:{message:socket hang up,code:ECONNRESET}}
{}
t = 4.618
trying to get supportFeatures...
{OpenDNSParentalControl:1.0,AccessControl:1.0,SpeedTest:2.0,GuestNetworkSchedule:1.0,AttachedDevice:2.0,NameNTGRDevice:1.0,TimeZone:2.0,MaxMonthlyTrafficLimitation:4095000000}
t = 4.716
trying to get the Device configuration...
{BlankState:0,NewBlockSiteEnable:0,NewTimeZone:+01,NewDaylightSaving:0}
t = 4.783
trying to get the LAN configuration...
{NewLANSubnet:255.255.255.0,NewLANIP:192.168.1.1,NewDHCPEnabled:1,NewWANLAN_Subnet_Match:1,NewLANMACAddress:8C3BAD3C55B0}
t = 4.877
trying to get the WAN configuration...
{NewEnable:1,NewConnectionType:DHCP,NewExternalIPAddress:192.168.137.30,NewSubnetMask:255.255.255.0,NewAddressingType:DHCP,NewDefaultGateway:192.168.137.1,NewMACAddress:8C3BAD3C55B2,NewMACAddressOverride:0,NewMaxMTUSize:1500,NewDNSEnabled:1,NewDNSServers:192.168.137.1}
t = 5.667
trying to get Parental Control Status...
Parental Control Enabled: false
t = 6.16
trying to get Qos Status...
Qos Enabled: false
t = 6.292
trying to get Qos Bandwidth options...
{newUplinkBandwidth:0,newDownlinkBandwidth:0,enabled:1}
t = 6.363
trying to get Device Access Control Status...
Block Device Enabled: true
t = 6.422
trying to get attachedDevices method 1...
Number of attached devices: 3
First attached device: {\IP\:\192.168.1.20\,\Name\:\BYT-HOMEY\,\MAC\:\C8:DF:84:3A:57:4C\,\ConnectionType\:\wireless\,\Linkspeed\:2,\SignalStrength\:100,\AllowOrBlock\:\Allow\}
t = 10.828
trying to get attachedDevices method 2...
Number of attached devices: 3
First attached device: {\IP\:\192.168.1.20\,\Name\:\BYT-HOMEY\,\NameUserSet\:false,\MAC\:\C8:DF:84:3A:57:4C\,\ConnectionType\:\2.4GHz\,\SSID\:\UPC247600817\,\Linkspeed\:2,\SignalStrength\:100,\AllowOrBlock\:\Allow\,\Schedule\:false,\DeviceType\:999,\Grouping\:0,\SchedulePeriod\:0}
t = 10.966
trying to get available and selected WiFi channels...
Available channels 2.4G-1: Auto,1,2,3,4,5,6,7,8,9,10,11,12,13
2.4G-1 channel is not available
Available channels 5.0G-1: Auto,36,40,44,48
5.0G-1 channel is not available
Available channels 5.0G-2: Auto,36,40,44,48
5.0G-2 channel is not available
t = 12.092
trying to get Smart Connect Status...
Smart Connect Enabled: false
t = 13.258
trying to get Guest Wifi Status...
2.4G-1 Guest wifi enabled: true
5.0G-1 Guest wifi is not available, method: 1
5.0G-2 Guest wifi is not available
t = 13.529
trying to get the Traffic Meter Enabled Status...
Traffic Meter Enabled: true
t = 14.259
trying to get the Traffic Meter Options...
{newControlOption:No Limit,newNewMonthlyLimit:0,restartHour:0,restartMinute:0,restartDay:1}
t = 14.359
trying to get trafficMeter...
{newTodayUpload:1.11,newTodayDownload:3.41,newMonthUpload:8388.03,newMonthDownload:17244.42}
t = 14.489
trying to check newFirmware...
check newFirmware method: 2
{currentVersion:V1.1.0.52,newVersion:,releaseNote:}
t = 18.665
trying to get router logs...
socket hang up
{lastResponse:{message:socket hang up,code:ECONNRESET}}
last log: undefined
t = 18.727
trying to logout...
{host:192.168.1.1,port:5000,tls:false,username:admin,password:*****,timeout:18000,sessionId:A7D88AE69687E58D9A00,cookie:true,loggedIn:false,configStarted:false,soapVersion:3,loginMethod:2,checkNewFirmwareMethod:2,guestWifiMethod:{get50_1:1},lastResponse:...}
t = 18.812
test finished with 3 errors

**Comment by gruijter** [comment]
The test after ptp shows that the r6350 firmware is very buggy concerning the soap interface ( that im using for the homey app). The router just randomly disconnects (econreset). And I cannot really see any specific command that is used in normal app mode thst triggers the hangup. So there is not much I can do about that. You could try older firmware, or get another router 🙈

And is it correct you only have 3 devices connected in your network?

**Comment by gruijter** [comment]
Or maybe as last resort I could make some of the app information content selectable. This would significantly reduce the app functionality, but might prevent the router from hanging up so fast.

**Comment by ma-be** [comment]
That sucks. I have bought the Netgear router with the idea to use your app with Homey. You should get some provision from Netgear :-).

And yes at the moment, there were only 3 devices connected.

**Comment by gruijter** [comment]
FYI, I'm working on a new version where you can disable functionality that could cause router hang-ups. Hang tight...

**Comment by ma-be** [comment]
Thank you.

**Comment by gruijter** [comment]
v3.0.3  Introduced selectable router capabilities for better compatibility with buggy router firmware.

Get it from Github now, or wait for the appstore release.

During router device pair, leave all the reporting options disabled.
Please let me know if this works for you.

**Comment by ma-be** [comment]
Thank you! The app v3.0.3 has been automaticly updated today.
I left the reporting options on default values (i.e. disabled).
First there was no change at all (only the logged messages were different).

Then I changed the "Attached devices method" setting from "Auto" to "New".  This way the number of "Attached devices" started to appear in the app and I was able to add the "Attached devices" to Homey. This way also the icons "CPU utilization" and "Traffic speed" disappeared.
But there was no info about Internet connection availability.

Then I changed the "Internet check" setting from "Netgear" to "Homey". This way the icon "Internet disconnected" started to show "No".

After while the added "attached devices" started to work and it seems good. I will monitor it and will let you know how it will behave. Hope it will be good :-).

But there are these errors in the app log:
2019-11-06 19:09:47 [netgear] [0] device init: R6350 id: *******
2019-11-06 19:08:47 [netgear] [0] watchdog triggered, restarting Homey device now
2019-11-06 19:07:47 [err] [ManagerDrivers] [netgear] [0] DevicePoll Error parsing device-list
2019-11-06 19:06:47 [err] [ManagerDrivers] [netgear] [0] DevicePoll Error parsing device-list
2019-11-06 19:05:47 [err] [ManagerDrivers] [netgear] [0] DevicePoll Error parsing device-list
2019-11-06 19:04:47 [err] [ManagerDrivers] [netgear] [0] DevicePoll Error parsing device-list
2019-11-06 19:03:48 [err] [ManagerDrivers] [netgear] [0] Error: Error parsing device-list at NetgearRouter._getAttachedDevices2 (/node_modules/netgear/netgear.js:1308:39) at at process._tickCallback (internal/process/next_tick.js:189:7)
2019-11-06 19:03:45 [netgear] [0] Access control enable requested
2019-11-06 19:03:45 [netgear] [0] retrieving knownDevices from persistent storage
2019-11-06 19:03:45 [netgear] [0] device init: R6350 id: *******
2019-11-06 19:02:45 [netgear] [0] watchdog triggered, restarting Homey device now
2019-11-06 19:01:46 [err] [ManagerDrivers] [netgear] [0] DevicePoll Error parsing device-list
2019-11-06 19:00:45 [err] [ManagerDrivers] [netgear] [0] DevicePoll Error parsing device-list
2019-11-06 18:59:45 [err] [ManagerDrivers] [netgear] [0] DevicePoll Error parsing device-list
2019-11-06 18:58:45 [err] [ManagerDrivers] [netgear] [0] DevicePoll Error parsing device-list
2019-11-06 18:57:46 [err] [ManagerDrivers] [netgear] [0] Error: Error parsing device-list at NetgearRouter._getAttachedDevices2 (/node_modules/netgear/netgear.js:1308:39) at at process._tickCallback (internal/process/next_tick.js:189:7)
2019-11-06 18:57:44 [netgear] [0] Access control enable requested
2019-11-06 18:57:44 [netgear] [0] retrieving knownDevices from persistent storage
2019-11-06 18:57:44 [netgear] [0] device init: R6350 id: *******
2019-11-06 18:56:44 [netgear] [0] watchdog triggered, restarting Homey device now

**Comment by ma-be** [comment]
“Device went offline” does not work properly :-(. There is no error in the log. But there are only 2 records in the log for the last 8 hours...


2019-11-07 08:44:17 [log] [MyApp] Retrieving known devices list 
2019-11-07 08:37:06 [log] [MyApp] Retrieving known devices list 
2019-11-06 23:55:10 [attached_device] [5] Disconnected: NTB-MABE 
2019-11-06 23:36:20 [log] [MyApp] Retrieving known devices list 


Interesting also is that the phone instead of “offline” (disconnected from wifi) is considered “wired”. 
![23810FC9-C803-4EE7-8F82-4DF8B5419658](https://user-images.githubusercontent.com/11045804/68369550-e3373b00-013a-11ea-9e07-d92642fea66e.jpeg)

**Comment by ma-be** [comment]
Another interesting observation: when I connect to the router via Nighthawk ios app, I see the correct status which devices are connected. Coincidently (?) from that time on, there is an error written to the homey netgear app log:

2019-11-07 09:15:52 [err] [ManagerDrivers] [netgear] [0] DevicePoll Error parsing device-list 
2019-11-07 09:14:52 [err] [ManagerDrivers] [netgear] [0] DevicePoll Error parsing device-list 
2019-11-07 08:44:17 [log] [MyApp] Retrieving known devices list 

Do these observations help you anyhow?

**Comment by gruijter** [comment]
![Screenshot_20191107-091603](https://user-images.githubusercontent.com/19174120/68380409-0fa98200-0150-11ea-9877-2fadd3a41ef3.png)

Try these settings, and always do a PTP of the router after changing these settings!

**Comment by gruijter** [comment]
@ma-be did above settings work for you?

**Comment by ma-be** [comment]
Hi @gruijter,
after an intesive testing I can confirm that your suggested settings (Internet check “Homey”, Attached devices method “Old”) work perfect.
Thank you!

**Comment by gruijter** [comment]
Whoohoo 🍻🎉👍😀
