### ISSUE TITLE
a lot of errors in 2.0.7

### ISSUE THREAD

**Issue by satbopper** [gruijter/com.gruijter.netgear#6]
err] [MyApp] unhandledRejection! TypeError: Cannot read property '0' of undefined at parseString (/node_modules/netgear/netgear.js:673:98) at Parser. (/node_modules/xml2js/lib/parser.js:303:18) at emitOne (events.js:116:13) at Parser.emit (events.js:211:7) at SAXParser.onclosetag (/node_modules/xml2js/lib/parser.js:261:26) at emit (/node_modules/sax/lib/sax.js:624:35) at emitNode (/node_modules/sax/lib/sax.js:629:5) at closeTag (/node_modules/sax/lib/sax.js:889:7) at SAXParser.write (/node_modules/sax/lib/sax.js:1436:13) at Parser.exports.Parser.Parser.parseString (/node_modules/xml2js/lib/parser.js:322:31) 
2018-10-18 21:22:39 [err] [MyApp] unhandledRejection! TypeError: Cannot read property '0' of undefined at parseString (/node_modules/netgear/netgear.js:673:98) at Parser. (/node_modules/xml2js/lib/parser.js:303:18) at emitOne (events.js:116:13) at Parser.emit (events.js:211:7) at SAXParser.onclosetag (/node_modules/xml2js/lib/parser.js:261:26) at emit (/node_modules/sax/lib/sax.js:624:35) at emitNode (/node_modules/sax/lib/sax.js:629:5) at closeTag (/node_modules/sax/lib/sax.js:889:7) at SAXParser.write (/node_modules/sax/lib/sax.js:1436:13) at Parser.exports.Parser.Parser.parseString (/node_modules/xml2js/lib/parser.js:322:31) 
2018-10-18 21:21:39 [err] [MyApp] unhandledRejection! TypeError: Cannot read property '0' of undefined at parseString (/node_modules/netgear/netgear.js:673:98) at Parser. (/node_modules/xml2js/lib/parser.js:303:18) at emitOne (events.js:116:13) at Parser.emit (events.js:211:7) at SAXParser.onclosetag (/node_modules/xml2js/lib/parser.js:261:26) at emit (/node_modules/sax/lib/sax.js:624:35) at emitNode (/node_modules/sax/lib/sax.js:629:5) at closeTag (/node_modules/sax/lib/sax.js:889:7) at SAXParser.write (/node_modules/sax/lib/sax.js:1436:13) at Parser.exports.Parser.Parser.parseString (/node_modules/xml2js/lib/parser.js:322:31) 
2018-10-18 21:20:39 [err] [MyApp] unhandledRejection! TypeError: Cannot read property '0' of undefined at parseString (/node_modules/netgear/netgear.js:673:98) at Parser. (/node_modules/xml2js/lib/parser.js:303:18) at emitOne (events.js:116:13) at Parser.emit (events.js:211:7) at SAXParser.onclosetag (/node_modules/xml2js/lib/parser.js:261:26) at emit (/node_modules/sax/lib/sax.js:624:35) at emitNode (/node_modules/sax/lib/sax.js:629:5) at closeTag (/node_modules/sax/lib/sax.js:889:7) at SAXParser.write (/node_modules/sax/lib/sax.js:1436:13) at Parser.exports.Parser.Parser.parseString (/node_modules/xml2js/lib/parser.js:322:31) 
2018-10-18 21:19:38 [err] [MyApp] unhandledRejection! TypeError: Cannot read property '0' of undefined at parseString (/node_modules/netgear/netgear.js:673:98) at Parser. (/node_modules/xml2js/lib/parser.js:303:18) at emitOne (events.js:116:13) at Parser.emit (events.js:211:7) at SAXParser.onclosetag (/node_modules/xml2js/lib/parser.js:261:26) at emit (/node_modules/sax/lib/sax.js:624:35) at emitNode (/node_modules/sax/lib/sax.js:629:5) at closeTag (/node_modules/sax/lib/sax.js:889:7) at SAXParser.write (/node_modules/sax/lib/sax.js:1436:13) at Parser.exports.Parser.Parser.parseString (/node_modules/xml2js/lib/parser.js:322:31) 
2018-10-18 21:18:38 [err] [MyApp] unhandledRejection! TypeError: Cannot read property '0' of undefined at parseString (/node_modules/netgear/netgear.js:673:98) at Parser. (/node_modules/xml2js/lib/parser.js:303:18) at emitOne (events.js:116:13) at Parser.emit (events.js:211:7) at SAXParser.onclosetag (/node_modules/xml2js/lib/parser.js:261:26) at emit (/node_modules/sax/lib/sax.js:624:35) at emitNode (/node_modules/sax/lib/sax.js:629:5) at closeTag (/node_modules/sax/lib/sax.js:889:7) at SAXParser.write (/node_modules/sax/lib/sax.js:1436:13) at Parser.exports.Parser.Parser.parseString (/node_modules/xml2js/lib/parser.js:322:31) 
2018-10-18 21:17:38 [err] [MyApp] unhandledRejection! TypeError: Cannot read property '0' of undefined at parseString (/node_modules/netgear/netgear.js:673:98) at Parser. (/node_modules/xml2js/lib/parser.js:303:18) at emitOne (events.js:116:13) at Parser.emit (events.js:211:7) at SAXParser.onclosetag (/node_modules/xml2js/lib/parser.js:261:26) at emit (/node_modules/sax/lib/sax.js:624:35) at emitNode (/node_modules/sax/lib/sax.js:629:5) at closeTag (/node_modules/sax/lib/sax.js:889:7) at SAXParser.write (/node_modules/sax/lib/sax.js:1436:13) at Parser.exports.Parser.Parser.parseString (/node_modules/xml2js/lib/parser.js:322:31) 
2018-10-18 21:16:38 [err] [MyApp] unhandledRejection! TypeError: Cannot read property '0' of undefined at parseString (/node_modules/netgear/netgear.js:673:98) at Parser. (/node_modules/xml2js/lib/parser.js:303:18) at emitOne (events.js:116:13) at Parser.emit (events.js:211:7) at SAXParser.onclosetag (/node_modules/xml2js/lib/parser.js:261:26) at emit (/node_modules/sax/lib/sax.js:624:35) at emitNode (/node_modules/sax/lib/sax.js:629:5) at closeTag (/node_modules/sax/lib/sax.js:889:7) at SAXParser.write (/node_modules/sax/lib/sax.js:1436:13) at Parser.exports.Parser.Parser.parseString (/node_modules/xml2js/lib/parser.js:322:31) 
2018-10-18 21:15:38 [err] [MyApp] unhandledRejection! TypeError: Cannot read property '0' of undefined at parseString (/node_modules/netgear/netgear.js:673:98) at Parser. (/node_modules/xml2js/lib/parser.js:303:18) at emitOne (events.js:116:13) at Parser.emit (events.js:211:7) at SAXParser.onclosetag (/node_modules/xml2js/lib/parser.js:261:26) at emit (/node_modules/sax/lib/sax.js:624:35) at emitNode (/node_modules/sax/lib/sax.js:629:5) at closeTag (/node_modules/sax/lib/sax.js:889:7) at SAXParser.write (/node_modules/sax/lib/sax.js:1436:13) at Parser.exports.Parser.Parser.parseString (/node_modules/xml2js/lib/parser.js:322:31) 
2018-10-18 21:14:38 [err] [MyApp] unhandledRejection! TypeError: Cannot read property '0' of undefined at parseString (/node_modules/netgear/netgear.js:673:98) at Parser. (/node_modules/xml2js/lib/parser.js:303:18) at emitOne (events.js:116:13) at Parser.emit (events.js:211:7) at SAXParser.onclosetag (/node_modules/xml2js/lib/parser.js:261:26) at emit (/node_modules/sax/lib/sax.js:624:35) at emitNode (/node_modules/sax/lib/sax.js:629:5) at closeTag (/node_modules/sax/lib/sax.js:889:7) at SAXParser.write (/node_modules/sax/lib/sax.js:1436:13) at Parser.exports.Parser.Parser.parseString (/node_modules/xml2js/lib/parser.js:322:31) 
2018-10-18 21:13:38 [err] [MyApp] unhandledRejection! TypeError: Cannot read property '0' of undefined at parseString (/node_modules/netgear/netgear.js:673:98) at Parser. (/node_modules/xml2js/lib/parser.js:303:18) at emitOne (events.js:116:13) at Parser.emit (events.js:211:7) at SAXParser.onclosetag (/node_modules/xml2js/lib/parser.js:261:26) at emit (/node_modules/sax/lib/sax.js:624:35) at emitNode (/node_modules/sax/lib/sax.js:629:5) at closeTag (/node_modules/sax/lib/sax.js:889:7) at SAXParser.write (/node_modules/sax/lib/sax.js:1436:13) at Parser.exports.Parser.Parser.parseString (/node_modules/xml2js/lib/parser.js:322:31) 
2018-10-18 21:12:38 [err] [MyApp] unhandledRejection! TypeError: Cannot read property '0' of undefined at parseString (/node_modules/netgear/netgear.js:673:98) at Parser. (/node_modules/xml2js/lib/parser.js:303:18) at emitOne (events.js:116:13) at Parser.emit (events.js:211:7) at SAXParser.onclosetag (/node_modules/xml2js/lib/parser.js:261:26) at emit (/node_modules/sax/lib/sax.js:624:35) at emitNode (/node_modules/sax/lib/sax.js:629:5) at closeTag (/node_modules/sax/lib/sax.js:889:7) at SAXParser.write (/node_modules/sax/lib/sax.js:1436:13) at Parser.exports.Parser.Parser.parseString (/node_modules/xml2js/lib/parser.js:322:31) 
2018-10-18 21:11:38 [err] [MyApp] unhandledRejection! TypeError: Cannot read property '0' of undefined at parseString (/node_modules/netgear/netgear.js:673:98) at Parser. (/node_modules/xml2js/lib/parser.js:303:18) at emitOne (events.js:116:13) at Parser.emit (events.js:211:7) at SAXParser.onclosetag (/node_modules/xml2js/lib/parser.js:261:26) at emit (/node_modules/sax/lib/sax.js:624:35) at emitNode (/node_modules/sax/lib/sax.js:629:5) at closeTag (/node_modules/sax/lib/sax.js:889:7) at SAXParser.write (/node_modules/sax/lib/sax.js:1436:13) at Parser.exports.Parser.Parser.parseString (/node_modules/xml2js/lib/parser.js:322:31) 
2018-10-18 21:10:38 [err] [MyApp] unhandledRejection! TypeError: Cannot read property '0' of undefined at parseString (/node_modules/netgear/netgear.js:673:98) at Parser. (/node_modules/xml2js/lib/parser.js:303:18) at emitOne (events.js:116:13) at Parser.emit (events.js:211:7) at SAXParser.onclosetag (/node_modules/xml2js/lib/parser.js:261:26) at emit (/node_modules/sax/lib/sax.js:624:35) at emitNode (/node_modules/sax/lib/sax.js:629:5) at closeTag (/node_modules/sax/lib/sax.js:889:7) at SAXParser.write (/node_modules/sax/lib/sax.js:1436:13) at Parser.exports.Parser.Parser.parseString

**Comment by satbopper** [comment]
oh yes router is r6300

**Comment by satbopper** [comment]
i installed 2.0.8 and it is with the setup ip,port not possible to login
went back to 2.0.7 with the same it is working again but those errors again

**Comment by gruijter** [comment]
@satbopper could you try again with 2.0.8 please? I updatet it on github so that it will provide more feedback for me on what is going on during an error. I especially need the 'last router response'. Could you post that when you get an error?

Thx much!

**Comment by satbopper** [comment]
the point is and i installed 2.0.8 21-10-2018,if i make a device with the input i use with the 2.0.7 version (what works) he coms back with the exclamation mark not logged in,so i can not make a device,the 2.0.8 version is installed

**Comment by satbopper** [comment]
the logfile with the 2.0.8 is as follows
2018-10-21 13:12:55 [log] [ManagerDrivers] [netgear] undefined 
2018-10-21 13:12:55 [log] [ManagerDrivers] [netgear] last repsonse from router: 
2018-10-21 13:12:55 [err] [ManagerDrivers] [netgear] Pair error Not logged in 
2018-10-21 13:12:55 [log] [ManagerDrivers] [netgear] using as soap host/port: 192.168.178.26:5000 
2018-10-21 13:12:55 [log] [ManagerDrivers] [netgear] {"Firmware":"V1.0.2.80_1.0.59","RegionTag":"R6300_WW","Region":"ww","Model":"R6300","InternetConnectionStatus":"Up","ParentalControlSupported":"1","SOAPVersion":"1.13","ReadyShareSupportedLevel":"5","SmartNetworkSupported":"0"}
2018-10-21 13:12:55 [log] [ManagerDrivers] [netgear] save button pressed in frontend 
2018-10-21 13:12:33 [log] [ManagerDrivers] [netgear] undefined 
2018-10-21 13:12:33 [log] [ManagerDrivers] [netgear] last repsonse from router: 
2018-10-21 13:12:33 [err] [ManagerDrivers] [netgear] Pair error HTTP request Failed. Status Code: 307 
2018-10-21 13:12:33 [log] [ManagerDrivers] [netgear] save button pressed in frontend 
2018-10-21 13:11:54 [log] [ManagerDrivers] [netgear] undefined 
2018-10-21 13:11:54 [log] [ManagerDrivers] [netgear] last repsonse from router: 
2018-10-21 13:11:54 [err] [ManagerDrivers] [netgear] Pair error HTTP request Failed. Status Code: 404 
2018-10-21 13:11:53 [log] [ManagerDrivers] [netgear] save button pressed in frontend 
2018-10-21 13:11:19 [log] [ManagerDrivers] [netgear] undefined 
2018-10-21 13:11:19 [log] [ManagerDrivers] [netgear] last repsonse from router: 
2018-10-21 13:11:19 [err] [ManagerDrivers] [netgear] Pair error Not logged in 
2018-10-21 13:11:19 [log] [ManagerDrivers] [netgear] using as soap host/port: 192.168.178.26:5000 
2018-10-21 13:11:19 [log] [ManagerDrivers] [netgear] {"Firmware":"V1.0.2.80_1.0.59","RegionTag":"R6300_WW","Region":"ww","Model":"R6300","InternetConnectionStatus":"Up","ParentalControlSupported":"1","SOAPVersion":"1.13","ReadyShareSupportedLevel":"5","SmartNetworkSupported":"0"}
2018-10-21 13:11:19 [log] [ManagerDrivers] [netgear] save button pressed in frontend 
2018-10-21 13:09:03 [log] [ManagerDrivers] [netgear] undefined 
2018-10-21 13:09:03 [log] [ManagerDrivers] [netgear] last repsonse from router: 
2018-10-21 13:09:03 [err] [ManagerDrivers] [netgear] Pair error Not logged in 
2018-10-21 13:09:03 [log] [ManagerDrivers] [netgear] using as soap host/port: 192.168.178.26:5000 
2018-10-21 13:09:03 [log] [ManagerDrivers] [netgear] {"Firmware":"V1.0.2.80_1.0.59","RegionTag":"R6300_WW","Region":"ww","Model":"R6300","InternetConnectionStatus":"Up","ParentalControlSupported":"1","SOAPVersion":"1.13","ReadyShareSupportedLevel":"5","SmartNetworkSupported":"0"}
2018-10-21 13:09:03 [log] [ManagerDrivers] [netgear] save button pressed in frontend 
2018-10-21 13:08:53 [log] [ManagerDrivers] [netgear] undefined 
2018-10-21 13:08:53 [log] [ManagerDrivers] [netgear] last repsonse from router: 
2018-10-21 13:08:53 [err] [ManagerDrivers] [netgear] Pair error Not logged in 
2018-10-21 13:08:53 [log] [ManagerDrivers] [netgear] using as soap host/port: 192.168.178.26:5000 
2018-10-21 13:08:53 [log] [ManagerDrivers] [netgear] {"Firmware":"V1.0.2.80_1.0.59","RegionTag":"R6300_WW","Region":"ww","Model":"R6300","InternetConnectionStatus":"Up","ParentalControlSupported":"1","SOAPVersion":"1.13","ReadyShareSupportedLevel":"5","SmartNetworkSupported":"0"}
2018-10-21 13:08:53 [log] [ManagerDrivers] [netgear] save button pressed in frontend 
2018-10-21 13:04:26 [err] [MyApp] error reading logfile: ENOENT: no such file or directory, open '/userdata/netgearLog.json' 
2018-10-21 13:04:26 [log] [ManagerDrivers] [netgear] NetgearDriver onInit 
2018-10-21 13:04:26 [log] [MyApp] Netgear App is running! 
2018-10-21 13:04:26 [log] [MyApp] capturing stderr
